name: Publish Weekly Stats

on:
  schedule:
    # https://crontab.guru/#0_12_*_*_1
    - cron: "0 12 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  comments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "18.x"
      
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - run: pnpm install
      
      # Update the site stats
      - run: node packages/typescriptlang-org/scripts/updateAppInsightsGitHubIssue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_INSIGHTS_API_KEY: ${{ secrets.APP_INSIGHTS_API_KEY }}
          APP_INSIGHTS_ID: ${{ secrets.APP_INSIGHTS_ID }}